### ISSUE TITLE
Repository contains files that are AGPL-licensed

### ISSUE THREAD

**Issue by amedee** [ymasory/iText-4.2.0#7]
The initial commit of this repository contains files that were taken from iText, after the switch to an AGPL license. Take for example https://github.com/ymasory/iText-4.2.0/blob/1095ce66fae02f2fc01e98863a141f456f680a10/test/core/com/itextpdf/testutils/TestResourceUtils.java, this file is identical to https://github.com/itext/itextpdf/blob/9de983d71e7537d4524c7b0a125366a13a75d111/itext/test/core/com/itextpdf/testutils/TestResourceUtils.java, which is timestamped in both repositories to Dec 21, 2009. The switch to AGPL happened on Dec 1, 2009, so `TestResourceUtils.java` falls under the AGPL license and cannot be included in an LGPL/MPL fork without prior consent of the copyright holder.

Other files with the same issue exist.

**Comment by andreasrosdalw** [comment]
This repository is based on the 4_2_0 svn branch/tag of iText which was hosted publicly on sourceforge. That branch is covered by the GNU Lesser General Public License and Mozilla Public License, because it has the license documents lgpl.txt and mpl.txt in it:

https://github.com/ymasory/iText-4.2.0/blob/master/src/core/com/lowagie/text/lgpl.txt
https://github.com/ymasory/iText-4.2.0/blob/master/www/lowagie/MPL-1.1.txt

(TestResourceUtils.java is not present in the master branch of OpenPDF, so it must have been removed before that fork was created.)

The iText 4_2_0 Svn tag can be seen [here](https://web.archive.org/web/20150923080043/http://sourceforge.net/p/itext/code/HEAD/tree/tags/) with the latest commit on 2009-12-21, which includes the mentioned TestResourceUtils.java. I also have a archived copy of the Svn checkout of the iText 4_2_0 Svn tag, which includes this file and the LGPL and MPL licenses.

**Comment by Lonzak** [comment]
So amedee what are the other files you are talking about? I think you have false assumptions here: There was a 5.0.0 branch created (or tagged) on 08 of december 2009 wich was licensed unter AGPL. However there was another branch 4.2.0 with the latest commits from 21st of december 2009. All commits from that branch are licensed under LGPL/MPL. 

But beside of that If you look at the header of the two files (and most of the others in that commit) you can read:

/*
 * Created on Dec 21, 2009
 * (c) 2009 Trumpet, Inc.
 *
 */

Just because trumpet Inc contributed those files under the new package name doesn't mean those where AGPL'ed. And besides iText corp. didn't even write this code - so you are taking copyright of files which you didn't even contribute?

I vote to close this issue.

**Comment by amedee** [comment]
I don't feel like adding fuel to Andreas Rosdal's personal vendetta against iText Software.
I vote to delete this issue.
